name: Default pipeline
on:
  push:
jobs:
  cache-and-install:
    name: Install and cache dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - uses: actions/cache@v3
        id: cache-nodemodules
        name: Setup node_modules cache
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm

      - name: Install dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: pnpm install
  type:
    name: Check types
    runs-on: ubuntu-latest
    needs: cache-and-install

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install pnpm
      uses: pnpm/action-setup@v2.0.1
      id: pnpm-install
      with:
        version: 7
        run_install: false

    - uses: actions/cache@v3
      id: cache-nodemodules
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm

    - name: Install dependencies
      if: steps.cache-nodemodules.outputs.cache-hit != 'true'
      run: pnpm install

    - name: Check types
      run: pnpm type
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: cache-and-install

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install pnpm
      uses: pnpm/action-setup@v2.0.1
      id: pnpm-install
      with:
        version: 7
        run_install: false

    - uses: actions/cache@v3
      id: cache-nodemodules
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm

    - name: Install dependencies
      if: steps.cache-nodemodules.outputs.cache-hit != 'true'
      run: pnpm install

    - name: Run lint
      run: pnpm lint
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: cache-and-install

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install pnpm
      uses: pnpm/action-setup@v2.0.1
      id: pnpm-install
      with:
        version: 7
        run_install: false

    - uses: actions/cache@v3
      id: cache-nodemodules
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm

    - name: Install dependencies
      if: steps.cache-nodemodules.outputs.cache-hit != 'true'
      run: pnpm install

    - name: Run test
      run: pnpm test